CREATE TABLE IF NOT EXISTS branch (
  LOCATION_ID VARCHAR(40),
  CITY VARCHAR(40),
  PRIMARY KEY (LOCATION_ID, CITY)
  );
  
CREATE TABLE IF NOT EXISTS VehicleType (
  VTNAME VARCHAR(40),
  FEATURES VARCHAR(40),
  WRATE INT,
  DRATE INT,
  HRATE INT,
  WIRATE INT,
  DIRATE INT,
  HIRATE INT,
  KRATE INT,
  PRIMARY KEY (VTNAME));
  
CREATE TABLE IF NOT EXISTS Vehicle(
  VID INT(13), 
  VLICENSE INT(13) UNIQUE, 
  MAKE VARCHAR(40),
  MODEL VARCHAR(40),
  YEAR VARCHAR(4),
  COLOR VARCHAR(40),
  ODOMETER INT, 
  STATUS_ID INT, 
  GASTYPE_ID INT, 
  VTNAME VARCHAR(40),
  LOCATION_ID VARCHAR(40),
  CITY VARCHAR(40),
  reserved BIT,
  PRIMARY KEY (VID), 
  FOREIGN KEY (VTNAME) REFERENCES VehicleType(VTNAME),
  FOREIGN KEY (LOCATION_ID, CITY) REFERENCES branch,
  FOREIGN KEY (STATUS_ID) REFERENCES CarStatus(STATUS_ID),
  FOREIGN KEY (GASTYPE_ID) REFERENCES GasType(GASTYPE_ID)
  );


CREATE TABLE IF NOT EXISTS CarStatus(
    STATUS_ID INT PRIMARY KEY,
    CAR_STATUS CHAR(20)
);

CREATE TABLE IF not exists GasType(
    GASTYPE_ID INT PRIMARY KEY,
    GASTYPE CHAR(32)
);

  
CREATE TABLE IF NOT EXISTS Customer(
  DLICENSE INT(13), 
  CELLPHONE INT(13),
  NAME_ID VARCHAR(40),
  ADDRESS_ID VARCHAR(40),
  PRIMARY KEY (DLICENSE)
  );
  
CREATE TABLE IF NOT EXISTS Reservations(
  CONFNO INT(13), 
  VTNAME VARCHAR(40),
  DLICENSE VARCHAR(40),
  FROMDATE DATE,
  FROMTIME TIME,
  TODATE DATE,
  TOTIME TIME,
  PRIMARY KEY (CONFNO),
  FOREIGN KEY (VTNAME) REFERENCES VehicleType,
  FOREIGN KEY (DLICENSE) REFERENCES Customer
  );
  
CREATE TABLE IF NOT EXISTS Rentals(
  RID INT(13), 
  VID INT(13),
  DLICENSE VARCHAR(40),
  FROMDATE DATE,
  FROMTIME TIME,
  TODATE DATE,
  TOTIME TIME,
  ODOMETER INT,
  CARDNO INT(13),
  CONFNO INT(13),
  PRIMARY KEY (RID),
  FOREIGN KEY (VID) REFERENCES Vehicle,
  FOREIGN KEY (DLICENSE) REFERENCES Customer,
  FOREIGN KEY (CONFNO) REFERENCES Reservations,
  FOREIGN KEY (CARDNO) REFERENCES Cards
  );

CREATE TABLE IF NOT EXISTS Cards(
    CARDNO CHAR(32) PRIMARY KEY,
    EXPDATE DATETIME,
    CARDNAME CHAR(32)
);
  
CREATE TABLE IF NOT EXISTS ReturnCar(
  RID INT(13),
  DATE_ID DATETIME,
  TIME_ID DATETIME,
  ODOMETER DATETIME,
  FULLTANK BIT,
  VALUE_ID INT(13),
  FOREIGN KEY (RID) REFERENCES Rentals(RID),
  PRIMARY KEY (RID)
  );  

  
  