create table branch (
  LOCATION_ID VARCHAR(40),
  CITY VARCHAR(40),
  PRIMARY KEY (LOCATION_ID, CITY)
  );
  
create table VehicleType (
  VTNAME VARCHAR(40),
  FEATURES VARCHAR(40),
  WRATE numeric(10,2),
  DRATE numeric(10,2),
  HRATE numeric(10,2),
  WIRATE numeric(10,2),
  DIRATE numeric(10,2),
  HIRATE numeric(10,2),
  KRATE numeric(10,2),
  PRIMARY KEY (VTNAME));
  
create table Vehicle(
  VID NUMBER(13),
  VLICENSE NUMBER(13), 
  MAKE VARCHAR(40),
  MODEL VARCHAR(40),
  YEAR NUMBER(13),
  COLOR VARCHAR(40),
  ODOMETER numeric(10,2),
  STATUS_ID VARCHAR(40),
  VTNAME VARCHAR(40),
  LOCATION_ID VARCHAR(40),
  CITY VARCHAR(40),
  PRIMARY KEY (VID),
  FOREIGN KEY (VTNAME) REFERENCES VehicleType,
  FOREIGN KEY (LOCATION_ID, CITY) REFERENCES branch
  );

create table Equipment(
  EID NUMBER(13),
  ETNAME VARCHAR(40),
  VTNAME VARCHAR(40),
  STATUS_ID VARCHAR(40),
  LOCATION_ID VARCHAR(40),
  CITY VARCHAR(40),
  DRATE numeric(10,2),
  HRATE numeric(10,2),
  PRIMARY KEY (EID),
  FOREIGN KEY (VTNAME) REFERENCES Vehicle,
  FOREIGN KEY (LOCATION_ID, CITY) REFERENCES branch
  );
  
create table Customer(
  DLICENSE NUMBER(13), 
  CELLPHONE NUMBER(13),
  NAME_ID VARCHAR(40),
  ADDRESS_ID VARCHAR(40),
  POINTS NUMBER(13)
  FEES numeric(10,2),
  PRIMARY KEY (DLICENSE)
  );
  
create table Reservations(
  CONFNO NUMBER(13), 
  VTNAME VARCHAR(40),
  DLICENSE VARCHAR(40),
  FROMDATE date,
  FROMTIME TIME [ ( p ) ],
  TODATE date,
  TOTIME TIME [ ( p ) ],
  HRATE numeric(10,2),
  EID NUMBER(13),
  PRIMARY KEY (EID),
  FOREIGN KEY (VTNAME) REFERENCES Vehicle,
  FOREIGN KEY (DLICENSE) REFERENCES Customer
  FOREIGN KEY (EID) REFERENCES Equipment
  );
  
create table Rentals(
  RID NUMBER(13), 
  VID NUMBER(13),
  EID NUMBER(13),
  DLICENSE VARCHAR(40),
  FROMDATE date,
  FROMTIME TIME [ ( p ) ],
  TODATE date,
  TOTIME TIME [ ( p ) ],
  ODOMETER numeric(10,2),
  CARDNAME VARCHAR(40),
  CARDNO NUMBER(13),
  EXPDATE date,
  CONFNO NUMBER(13),
  PRIMARY KEY (RID),
  FOREIGN KEY (VID) REFERENCES Vehicle,
  FOREIGN KEY (DLICENSE) REFERENCES Customer,
  FOREIGN KEY (CONFNO) REFERENCES Reservations
  );
  
create table Returns(
  RID NUMBER(13),
  DATE_ID date,
  TIME_ID TIME [ ( p ) ],
  ODOMETER numeric(10,2),
  FULLTANK VARCHAR(40),
  VALUE_ID NUMBER(13),
  FOREIGN KEY (RID) REFERENCES Rentals
  );  

  
  